Title: Asciimplicity
Origin: Typst
Year: 2026
Genre: Steam Grid Generator
Author: Madeline Hashcube
Singleplayer: ~
Online: ~
Local: ~
Drawing: |
  for color in (
      palette.rosewater, palette.flamingo, palette.pink, palette.mauve,
      palette.red, palette.peach, palette.yellow, palette.green,
      palette.teal, palette.sky, palette.sapphire, palette.blue,
      palette.lavender, palette.text, palette.subtext1, palette.subtext0,
  ) { for _ in range(30) { text(fill: color.rgb)[@] }; [\ ] }
